export const ALIAS_MAP: { [key: string]: string } = {
    "AI": "ai",
    "priv": "privilege",
    "ses": "session",
    "st": "set",
    "ck": "check",
    "clr": "clear",
    "sb": "standby",
    "fgt": "forget",
    "f": "forget",
    "ass": "assistant",
    "img": "image",
    "memo": "memory",
    "cons": "consolidate",
    "p": "private",
    "g": "group",
    "del": "delete",
    "ign": "ignore",
    "rm": "remove",
    "lst": "list",
    "tk": "token",
    "y": "year",
    "m": "month",
    "lcl": "local",
    "ran": "random",
    "nick": "nickname"
}
