const fs = require('fs');
const path = require('path');
const root = process.cwd();

// 模块头部注释表：相对路径 -> 说明
const headers = {
  'src/index.ts': '// 插件入口：注册配置、工具、命令与事件处理器，并启动各模块（含智能体初始化）',
  'src/logger.ts': '// 日志模块：统一封装 seal 插件日志输出（debug/info/warning/error）',
  'src/timer.ts': '// 定时器模块：目标/间隔/活跃时间段三类定时任务的调度与持久化',
  'src/trigger.ts': '// 触发相关模块（预留）',
  'src/update.ts': '// 版本更新日志（updateInfo），供启动时展示更新说明',
  'src/usage.ts': '// token 用量统计：按模型按天记录，支持过期归并/汇总/图表',
  'src/agent/agent.ts': '// 智能体（Agent）：角色配置 + 会话服务，chat() 按 use 选择模型发起对话',
  'src/agent/stream.ts': '// 流式/非流式请求服务：基于 Model 配置构建请求体并调用后端',
  'src/agent/agents/index.ts': '// 智能体注册入口：副作用导入即完成各智能体的初始化',
  'src/agent/agents/compress_agent.ts': '// 压缩智能体：用于压缩过长的用户消息（use=compression）',
  'src/agent/agents/samples.ts': '// 示例智能体：示例命令展示用（use=chat）',
  'src/agent/agents/summarize_agent.ts': '// 摘要智能体：用于短期记忆总结（use=summarization）',
  'src/cmd/privilege.ts': '// 命令权限系统：命令权限定义、存储与校验',
  'src/cmd/root_cmd.ts': '// 根命令 .ai：子命令注册与分发、会话上下文组装',
  'src/cmd/sub_cmd/ctxn.ts': '// .ai ctxn：上下文内名字自动修改相关',
  'src/cmd/sub_cmd/forget.ts': '// .ai forget：遗忘（清除）上下文',
  'src/cmd/sub_cmd/ignore.ts': '// .ai ignore：群内忽略名单管理',
  'src/cmd/sub_cmd/image.ts': '// .ai image：图片管理（本地/偷取/识别/查找）',
  'src/cmd/sub_cmd/memory.ts': '// .ai memo：个人/群聊/短期记忆与设定管理',
  'src/cmd/sub_cmd/model.ts': '// .ai model：查看/设置当前会话使用的模型（按会话覆盖）',
  'src/cmd/sub_cmd/off.ts': '// .ai off：关闭 AI（整体或按模式）',
  'src/cmd/sub_cmd/on.ts': '// .ai on：开启 AI 及计数器/计时器/概率/活跃时间模式',
  'src/cmd/sub_cmd/privilege.ts': '// .ai priv：会话/指令权限修改',
  'src/cmd/sub_cmd/prompt.ts': '// .ai prompt：查看当前 system prompt',
  'src/cmd/sub_cmd/role.ts': '// .ai role：切换角色设定',
  'src/cmd/sub_cmd/sample.ts': '// .ai sample：查看示例智能体（受示例开关控制）',
  'src/cmd/sub_cmd/shut.ts': '// .ai shut：打断当前流式对话',
  'src/cmd/sub_cmd/standby.ts': '// .ai standby：开启待机模式（记录对话内容）',
  'src/cmd/sub_cmd/status.ts': '// .ai status：查看当前会话 AI 状态',
  'src/cmd/sub_cmd/timer.ts': '// .ai timer：查看/清除定时器',
  'src/cmd/sub_cmd/token.ts': '// .ai token：查看/清除 token 用量记录',
  'src/cmd/sub_cmd/tool.ts': '// .ai tool：查看/开关/调用工具函数',
  'src/config/config.ts': '// 配置中心：按模块注册 seal 配置并缓存，动态挂载 Config.<模块> 访问器',
  'src/config/static_config.ts': '// 静态常量：版本/作者/模型映射表/权限等级/别名/表情表等',
  'src/config/configs/base.ts': '// 基础配置：日志级别/超时/SealDice 路径/全局待机',
  'src/config/configs/model.ts': '// 模型配置：对话/图片/嵌入模型 TOML 解析，并同步 Model 静态列表',
  'src/config/configs/backend.ts': '// 后端服务配置：流式/图片转base64/搜索/用量图/渲染等 URL',
  'src/config/configs/received.ts': '// 消息接收配置：接收范围/忽略条件与正则',
  'src/config/configs/trigger.ts': '// 触发配置：默认计数器/计时器/概率/活跃时间/触发正则与令牌桶',
  'src/config/configs/image.ts': '// 图片配置：识别条件/base64转换/本地图片/发送概率/偷取上限',
  'src/config/configs/tool.ts': '// 工具配置：函数调用开关/提示词工程/上限/禁用与默认关闭/本地录音路径',
  'src/config/configs/memory.ts': '// 记忆配置：向量维度/长期记忆/总结记忆/知识库 TOML',
  'src/config/configs/reply.ts': '// 回复配置：引用/最大字数/去空白/复读检测/过滤正则与模板',
  'src/config/configs/message.ts': '// 对话配置：角色设定/示例对话/轮数/插入间隔/展示号码/压缩阈值',
  'src/config/configs/prompt.ts': '// prompt 模板配置：system/记忆/总结/知识库/工具/图片识别等 Handlebars 模板',
  'src/config/configs/resource.ts': '// 资源配置：本地图片/语音路径（供 system prompt 列出可发送资源）',
  'src/config/configs/sample.ts': '// 示例开关配置',
  'src/context/context.ts': '// 会话上下文：消息增删/忽略名单/压缩与总结触发/用户群查找/图片查找',
  'src/context/message.ts': '// 消息结构工具：消息类型判断等静态方法',
  'src/context/types.ts': '// 上下文消息类型定义',
  'src/memory/memory.ts': '// 记忆服务：MemoryItem 存取/检索/权重/短期记忆（含旧格式迁移）',
  'src/memory/knowledge.ts': '// 知识库服务：按角色加载知识库记忆与检索（继承记忆服务）',
  'src/memory/memory_item.ts': '// 记忆条目：向量/标签/用户群组/相似度与新鲜度计算',
  'src/memory/session_memory.ts': '// 会话记忆：短期记忆总结（调用摘要智能体）与记忆 prompt 构建',
  'src/memory/types.ts': '// 记忆类型定义',
  'src/model/model.ts': '// 模型管理器：按 use/名称选择对话/图片/嵌入模型',
  'src/model/chat.ts': '// 对话模型：callChat 构建请求并解析响应',
  'src/model/image.ts': '// 图片模型：图片理解（callITT）与图片对话',
  'src/model/embedding.ts': '// 嵌入模型：文本向量化（带缓存）',
  'src/model/types.ts': '// 模型类型定义',
  'src/resource/image.ts': '// 图片资源：URL/base64/本地路径图片，图片识别与存储',
  'src/session/session.ts': '// 会话：聊天编排（chat/chatStream/回复/接收）、设定、工具状态与活跃时间',
  'src/session/session_service.ts': '// 会话服务：会话的创建/复活/保存，getSession 入口与知识库访问',
  'src/session/types.ts': '// 会话/用户/群类型定义',
  'src/session/user.ts': '// 用户档案：存储与读取',
  'src/session/group.ts': '// 群档案：存储与读取',
  'src/tool/tool.ts': '// 工具系统：Tool 注册表、工具调用（含扩展指令/提示词工程）与注册',
  'src/tool/types.ts': '// 工具类型定义',
  'src/tool/tools/builtin_cmd.ts/init.ts': '// 内置指令工具注册入口（jrrp 懒注册）',
  'src/tool/tools/builtin_cmd.ts/jrrp.ts': '// jrrp 工具：今日人品（懒注册，避免加载期循环引用）',
  'src/tool/tools/builtin_cmd.ts/tool_attr.ts': '// 属性工具：coc 属性展示/获取/修改',
  'src/tool/tools/builtin_cmd.ts/tool_modu.ts': '// 模组工具：COC 模组抽取/搜索',
  'src/tool/tools/builtin_cmd.ts/tool_roll_check.ts': '// 检定工具：技能/属性检定与 san check',
  'src/tool/tools/image.ts/tool_image.ts': '// 图片工具：图片转文字/文生图（AIDrawing）',
  'src/tool/tools/image.ts/tool_meme.ts': '// 表情包工具：列表/信息/制作（meme 服务）',
  'src/tool/tools/image.ts/tool_render.ts': '// 渲染工具：Markdown/HTML 转图片',
  'src/tool/tools/ob11.ts/tool_ban.ts': '// 禁言工具：禁言/全员禁言/禁言列表',
  'src/tool/tools/ob11.ts/tool_essence_msg.ts': '// 精华消息工具：设置/获取/删除',
  'src/tool/tools/ob11.ts/tool_group_sign.ts': '// 群打卡工具',
  'src/tool/tools/ob11.ts/tool_person_info.ts': '// 个人信息工具：资料/生日/星座等',
  'src/tool/tools/ob11.ts/tool_qq_list.ts': '// 列表工具：好友/群/成员/共同群搜索',
  'src/tool/tools/ob11.ts/tool_rename.ts': '// 改名工具：设置群名片',
  'src/tool/tools/seal.ts/tool_deck.ts': '// 牌堆工具：抽取牌堆',
  'src/tool/tools/sample.ts': '// 示例工具（未注册）',
  'src/tool/tools/tool_context.ts': '// 上下文工具：查看指定会话上下文',
  'src/tool/tools/tool_memory.ts': '// 记忆工具：添加/删除/搜索/清除记忆（含知识库）',
  'src/tool/tools/tool_message.ts': '// 消息工具：发送消息/取消息/撤回/合并转发',
  'src/tool/tools/tool_music.ts': '// 点歌工具',
  'src/tool/tools/tool_time.ts': '// 时间/定时器工具：当前时间与目标/间隔定时器设置',
  'src/tool/tools/tool_trigger.ts': '// 触发条件工具：AI 自行设定的触发条件',
  'src/tool/tools/tool_voice.ts': '// 语音工具：本地语音/文字转语音（TTS）',
  'src/tool/tools/tool_web.ts': '// 联网工具：搜索与网页阅读',
  'src/utils/utils.ts': '// 通用工具：消息ID转换/回复发送/超时/revive/路径解析等',
  'src/utils/message.ts': '// 消息构建：system prompt/上下文消息组装与 body 解析',
  'src/utils/string.ts': '// 字符串工具：消息段转换/回复拆分过滤/复读检测等',
  'src/utils/seal.ts': '// seal 上下文工具：构造 ctx/msg/会话ID',
  'src/utils/ob11.ts': '// ob11 API 封装：消息/群/好友/禁言等',
  'src/utils/update.ts': '// 版本校验与更新日志展示',
  'src/utils/web.ts': '// 网络请求封装（fetch）',
};

let added = 0;
for (const [rel, comment] of Object.entries(headers)) {
  const p = path.join(root, rel);
  if (!fs.existsSync(p)) { console.log('跳过(不存在):', rel); continue; }
  let s = fs.readFileSync(p, 'utf8');
  // 已存在相同头注释则跳过
  if (s.startsWith(comment.split('\n')[0])) continue;
  s = comment + '\n' + s;
  fs.writeFileSync(p, s);
  added++;
}
console.log('已添加头部注释文件数:', added);
